name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: pip install uv

    - name: Install project with uv
      run: uv pip install --system -e .

    - name: Run tests with local path
      run: PYTHONPATH=src pytest --maxfail=1 --disable-warnings --no-header -q
